require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkingChangesController do

  # This should return the minimal set of attributes required to create a valid
  # WorkingChange. As you add validations to WorkingChange, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorkingChangesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all working_changes as @working_changes" do
      working_change = WorkingChange.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:working_changes)).to eq([working_change])
    end
  end

  describe "GET show" do
    it "assigns the requested working_change as @working_change" do
      working_change = WorkingChange.create! valid_attributes
      get :show, {:id => working_change.to_param}, valid_session
      expect(assigns(:working_change)).to eq(working_change)
    end
  end

  describe "GET new" do
    it "assigns a new working_change as @working_change" do
      get :new, {}, valid_session
      expect(assigns(:working_change)).to be_a_new(WorkingChange)
    end
  end

  describe "GET edit" do
    it "assigns the requested working_change as @working_change" do
      working_change = WorkingChange.create! valid_attributes
      get :edit, {:id => working_change.to_param}, valid_session
      expect(assigns(:working_change)).to eq(working_change)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WorkingChange" do
        expect {
          post :create, {:working_change => valid_attributes}, valid_session
        }.to change(WorkingChange, :count).by(1)
      end

      it "assigns a newly created working_change as @working_change" do
        post :create, {:working_change => valid_attributes}, valid_session
        expect(assigns(:working_change)).to be_a(WorkingChange)
        expect(assigns(:working_change)).to be_persisted
      end

      it "redirects to the created working_change" do
        post :create, {:working_change => valid_attributes}, valid_session
        expect(response).to redirect_to(WorkingChange.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved working_change as @working_change" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkingChange.any_instance.stub(:save).and_return(false)
        post :create, {:working_change => {  }}, valid_session
        expect(assigns(:working_change)).to be_a_new(WorkingChange)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkingChange.any_instance.stub(:save).and_return(false)
        post :create, {:working_change => {  }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested working_change" do
        working_change = WorkingChange.create! valid_attributes
        # Assuming there are no other working_changes in the database, this
        # specifies that the WorkingChange created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WorkingChange.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => working_change.to_param, :working_change => { "these" => "params" }}, valid_session
      end

      it "assigns the requested working_change as @working_change" do
        working_change = WorkingChange.create! valid_attributes
        put :update, {:id => working_change.to_param, :working_change => valid_attributes}, valid_session
        expect(assigns(:working_change)).to eq(working_change)
      end

      it "redirects to the working_change" do
        working_change = WorkingChange.create! valid_attributes
        put :update, {:id => working_change.to_param, :working_change => valid_attributes}, valid_session
        expect(response).to redirect_to(working_change)
      end
    end

    describe "with invalid params" do
      it "assigns the working_change as @working_change" do
        working_change = WorkingChange.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkingChange.any_instance.stub(:save).and_return(false)
        put :update, {:id => working_change.to_param, :working_change => {  }}, valid_session
        expect(assigns(:working_change)).to eq(working_change)
      end

      it "re-renders the 'edit' template" do
        working_change = WorkingChange.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkingChange.any_instance.stub(:save).and_return(false)
        put :update, {:id => working_change.to_param, :working_change => {  }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested working_change" do
      # working_change = WorkingChange.create! valid_attributes
      # expect {
      #   delete :destroy, {:id => working_change.to_param}, valid_session
      # }.to change(WorkingChange, :count).by(-1)
      pending
    end

    it "redirects to the working_changes list" do
      working_change = WorkingChange.create! valid_attributes
      delete :destroy, {:id => working_change.to_param}, valid_session
      expect(response).to redirect_to(tables_url)
    end
  end

end
